console.log("Javascript")
// alert("hello")
// prompt("what is your name?")
// console.log('my name')
// console.log("my name")
// console.log(`my name`)
// console.log('i\'m here')
// console.log(typeof("string1"))
// console.log(typeof(null))
// console.log(10.25+2.25)
// console.log("my name is" +" "+ "Adejare")
// console.log(3*1+2)
// console.log(true&&false)
// console.log(false&&true)
// console.log(false&&false)
// console.log(true&&true)
console.log(false||false)
console.log(!true)
console.log(!false)
console.log(!true&&true||false)